controller_list:
  - name: "gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [left_finger_joint

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
  
gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:  
    - left_finger_joint
       